### ISSUE TITLE
naming a warp point 'name' will crash the game

### ISSUE THREAD

**Issue by sakamakj** [badgamernl/explosivegaming-main#60]
**Error Message**
Error while running event level::on_tick(ID 0)
...Data/Roaming/Factorio/temp/currently-playing/control.lua:14:attempt to concatenate local 'err'/a table value)
**Known Causes**
Know causes that will result in error:
 - typing /make-warp name

**To Reproduce (please give for each cause outlined above)**
 - Cause 1
    1. Open a game that has the latest version of the script 
    2. type /make-warp name

**Other information (please complete the following information):**
 - Windows, +whatever ExplosingGaming is running on
 - Factorio Version: [0.16.45]

**Additional context**
It has crashed one explosiveGaming server (s2) today (2018-05-26) while Gizan was playing.

**Comment by Cooldude2606** [comment]
The problem of the crash was due to an error in the error handdle within the core files so that was a luckly find as any error would have crashed the server. [See fix.](https://github.com/badgamernl/explosivegaming-main/commit/a86787509e6fc477cae1af1ac6bc3aff22ed88a8)
The warp problem was an easy fix just added some valadation to which names could be used, there may be other areas where this problem will arise. [See fix.](https://github.com/badgamernl/explosivegaming-main/commit/9041006c5a37af0fa1fb2dc2ba18ce3616ca46b1)
